name: Pull request workflow

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: '0'

      - name: Setup java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Run verifications
        run: ./gradlew check

      - name: Upload reports
        uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'